#NOT OPERATOR

a=-1


if not a:
    print(True)

else:
    print(False)
    

#OR OPERATOR

b=10
v=-10

if b>5 or v>10:
    print("Working")


else:
    print("NOt Working!")

#AND OPERATOR

c=3
n=2

if c>1 and n>1:
    print("And operator is working!")

else:
    print("And operator is not working!")


#Write a program to check whether the given values have boolean values or not.

r=12
t=13
g=18

if r and t and g:
    print("all the numbers have boolean value  as true")

else:
    print("boolean values are false")

t=12
w=-12
f=81

if t>w or f>w:
    print("either of the number is greater")

else:
    print("either of the number is smaller")    

    